hacknctweetsbl/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', RedirectView.as_view(url='tweet/', permanent=False), name='indexT'),
    url(r'^tweet/', include('tweet.urls', namespace="tweet")),
]

tweet/urls.py
from django.conf.urls import include, url
from . import views
urlpatterns = [
    # Examples:
    # url(r'^$', 'easy_ecom.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.index, name= "index"),

]

tweet/models.py
from django.db import models

# Create your models here.

tweet/forms.py
from django import forms

class SearchForm(forms.Form):

    search = forms.CharField(label='Search for',
                               max_length=100,
                               required= True)

tweet/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from tweet.forms import SearchForm
from tweet.bluemix_sensitive import *
import urllib.parse
import json
from collections import defaultdict
import requests
import datetime
import queue

# Create your views here.

class Tweet:
    def __init__(self):
        self.tweets = defaultdict(int)

    def get_tweets(self):
        return dict(self.tweets)

def open_url(search):
    today = datetime.datetime.today()
    two_days_before = today - datetime.timedelta(days=2)
    print("today ", today, " two days before ", two_days_before)
    str_tif = "%d-%02d-%02dT%02d:%02d:%02dZ" %(two_days_before.year, two_days_before.month, two_days_before.day, \
                     two_days_before.hour, two_days_before.minute, two_days_before.second)
    top_level_url = twitter_search_base_url + "?q=" + urllib.parse.quote(search, safe='')\
                    + "%20AND%20posted:" + urllib.parse.quote(str_tif, safe='') \
                    + "&size=100"
    print("url ", top_level_url)
    r = requests.get(top_level_url, auth= (twitter_username, twitter_password))
    tweet_list, tweets_raw_list = [], []
    pq = queue.PriorityQueue()
    hashtags = defaultdict(int)
    if r.status_code == 200:
        data_json = r.json()
        for tweet in data_json['tweets']:
            tw = tweet['message']['body']
            tweets_raw_list.append(tw)
            t = Tweet()
            for word in tw.split():
                if word[0] == "#":
                    hashtags[word.lower()] += 1
                    t.tweets[word.lower()] += 1
            tweet_list.append(tweet_list)
        hashtags = dict(hashtags)

    return hashtags, tweets_raw_list


def get_relevant_hastags(hashtags):
    rel_tags, max_iter={}, 100
    for i in range(0, 2):
        if len(hashtags) > 0:
            mx = max(hashtags, key= hashtags.get)
            rel_tags[mx] = hashtags[mx]
            hashtags.pop(mx)
    return rel_tags

def get_sentiment_analysis(tags):
    today = datetime.datetime.today()
    two_days_before = today - datetime.timedelta(days=2)
    print("today ", today, " two days before ", two_days_before)
    str_tif = "%d-%02d-%02dT%02d:%02d:%02dZ" %(two_days_before.year, two_days_before.month, two_days_before.day, \
                     two_days_before.hour, two_days_before.minute, two_days_before.second)
    tag_str = ' OR '.join([x for x in tags.keys()])
    top_level_url_positive = twitter_count_base_url + "?q=(" + urllib.parse.quote(tag_str, safe='')\
                    + ")%20AND%20posted:" + urllib.parse.quote(str_tif, safe='') \
                    + "%20AND%20sentiment:positive"
    top_level_url_negative = twitter_count_base_url + "?q=(" + urllib.parse.quote(tag_str, safe='')\
                    + ")%20AND%20sentiment:negative" +"%20AND%20posted:" + urllib.parse.quote(str_tif, safe='')
    r_positive = requests.get(top_level_url_positive, auth= (twitter_username, twitter_password))
    r_negative = requests.get(top_level_url_negative, auth= (twitter_username, twitter_password))
    print(top_level_url_positive, top_level_url_negative)
    if r_positive.status_code == 200 and r_negative.status_code == 200:
        data_json = r_positive.json()
        positive_score = data_json['search']['results']
        data_json = r_negative.json()
        negative_score = data_json['search']['results']
        rating = "%.2f" %(positive_score/(positive_score + negative_score))
        return rating, (positive_score + negative_score)
    print(r_positive.status_code, r_negative.status_code)
    return None

def index(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = SearchForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            out_dict = {}
            search = form.cleaned_data['search']
            try:
                hashtags, tweets_raw_list = open_url(search)
                rel_tags = get_relevant_hastags(hashtags)
                rating, total = get_sentiment_analysis(rel_tags)
                out_dict = {'rating' : rating, 'total': total, 'rel_tags': ', '.join(rel_tags.keys())}
            except Exception:
                pass
            return render(request, 'tweet/search_result.html', out_dict)
    # if a GET (or any other method) we'll create a blank form
    else:
        form = SearchForm()

    return render(request, 'tweet/index.html', {'form': form})

tweet/templates/tweet/base.html
<!DOCTYPE html>
<html>
{% load static from staticfiles %}
<head lang="en">
    {% block head %}{% endblock %}
    <meta charset="UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <title>{% block title %}{% endblock %}</title>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.js" type="text/javascript"></script>
</head>
<body style="background-color: #EEF9FF">

<nav class="navbar navbar-inverse">
    <div class="container">
  <div class="container-fluid">
    <div class="navbar-header">
       <a class="navbar-brand" href="{% url 'tweet:index' %}">
<p >HACKNC Event Rater</p>
      </a>
    </div>
</div>
  </div>
</nav>

<div class="container">
      {% block body %}{% endblock %}
        {% block searchForm %}{% endblock %}
</div>

</body>
</html>

tweet/templates/tweet/index.html
{% extends "tweet/base.html" %}

{% block title %}Search{% endblock %}

{% block body %}
<div class="row">
    <div class="col-md-6 col-lg-6 center-block">
<p>Get the rating for events or some trending stuffs.</p>
        </div>
</div>
{% endblock %}

{% block searchForm %}
<form action="{% url 'tweet:index' %}" method="post" role="form">
    {% csrf_token %}

    <div class="row">
        <div class="col-lg-12 col-md-12">
    <div class="form-group">
    <!--{{ form }}-->

    <p><label for="{{form.search.id_for_label}}"></label></p>
        <div class="row">
            <div class="col-lg-7">
               <!--{{form.search}}-->
        <input class="form-control input-lg" name="search" id="{{form.search.id_for_label}}" type="text"/>
                </div>

            <div class="col-lg-2">
    <button type="submit" class="btn btn-success btn-block btn-lg" >Search</button>
                </div>
            <div class="col-lg-3">
    <p>{{ form.search.errors }}</p>
                </div>
            </div>
        </div>
</div>
        </div>
    <p>Eg: Search for hacknc</p>
</form>


{% endblock %}

{{form}}

tweet/templates/tweet/search_result.html
{% extends "tweet/base.html" %}
<!--<br><br>-->
<!--{% for hashtag, count in hashtags.items %}-->
<!--<p>{{ hashtag }} and repeated for {{count}} time.</p>-->
<!--{% endfor %}-->
<!--<p>rel tags</p>-->

<!--<p>tweets</p>-->
<!--{% for tweets in tweets_raw_list %}-->
<!--<p>{{ tweets }}</p>-->
<!--{% endfor %}-->

{% block title %}Search{% endblock %}

{% block body %}
{% if total %}
    <p>Based on analysing {{total}} tweets, Rating is {{rating}}</p>
<p>Searched for {{rel_tags}} tags in twitter for analysing.</p>
{% else %}
    <p>Search term yielded zero results. Try for something else.</p>
{% endif %}
<p><a href="{% url 'tweet:index' %}">Search again</a></p>
{% endblock %}

{{form}}